---
- name: 1.创建k8s工作、证书、配置文件、日志等目录
  file: dest={{ k8s_work_dir }}/{{ item }} state=directory
  with_items:
  - bin
  - cfg
  - ssl
  - logs

- name: 1.创建 kubeconfig 目录
  file: dest={{ item }} state=directory
  with_items:
  - "/root/.kube"

# 如果master节点和etcd重叠使用，etcd将存在两份相同证书
- name: 创建 etcd 证书目录
  file: dest={{ k8s_work_dir }}/ssl/etcd state=directory

- name: 1-2.创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 2.分发证书工具 cfssl
  unarchive: src={{ software_dir }}/cfssl.tar.gz dest=/usr/local/bin/ mode=u+x

- name: 2-2.分发并解压k8s二进制包
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/kubernetes-*.tar.gz"
  tags: kube-tools

- name: 2-3.分发 k8s master 二进制文件
  shell: cp -rf {{ tmp_dir }}/kubernetes/server/bin/{kubectl,kubeadm} /usr/local/bin/
  tags: kube-tools

- block:
    - name: 分发部署集群时使用到的相关证书
      copy: src={{ base_dir }}/ssl/{{ item }} dest={{ k8s_work_dir }}/ssl/{{ item }}
      with_items:
      - admin.pem
      - admin-key.pem
      - ca.pem
      - ca-key.pem
      - ca-config.json
      - kubernetes.pem
      - kubernetes-key.pem
      - kube-controller-manager.pem
      - kube-controller-manager-key.pem
      - kube-scheduler.pem
      - kube-scheduler-key.pem
      - proxy-client.pem
      - proxy-client-key.pem
    
    # 这里的etcd证书和部署etcd集群的role种的相同，但是存放目录路径不同；
    # 这样做是为了以防部署etcd集群和master集群节点复用时，需要改写playbook；
    # 这里分发etcd证书是不复用master集群节点时的情况;
    # 如果注销，需要修改kube-apiserver.service (kube-apiserver.conf)文件，重新指定etcd证书路径.
    - name: 分发etcd证书
      copy: src={{ base_dir }}/ssl/{{ item }} dest={{ k8s_work_dir }}/ssl/etcd
      with_items:
      - etcd.pem
      - etcd-key.pem
      when: "inventory_hostname in groups['master']"

    - name: 分发 kubeconfig配置文件
      copy: src=/root/.kube/config dest=/root/.kube/config

    - name: 分发 kube-proxy.kubeconfig配置文件
      copy: src={{ base_dir }}/ssl/kube-proxy.kubeconfig dest={{ k8s_work_dir }}/cfg/kube-proxy.kubeconfig

    - name: 分发 kube-controller-manager.kubeconfig配置文件
      copy: src={{ base_dir }}/ssl/kube-controller-manager.kubeconfig dest={{ k8s_work_dir }}/cfg/kube-controller-manager.kubeconfig
      when: "inventory_hostname in groups['master']"

    - name: 分发 kube-scheduler.kubeconfig配置文件
      copy: src={{ base_dir }}/ssl/kube-scheduler.kubeconfig dest={{ k8s_work_dir }}/cfg/kube-scheduler.kubeconfig
      when: "inventory_hostname in groups['master']"
  when: "inventory_hostname in groups['master'] or inventory_hostname in groups['node']"
