# apiserver 使用 vip + nginx 代理
KUBE_APISERVER: "https://{{ vip }}:8443"

# 设置 svc ip (这里选用 SERVICE_CIDR 中第1个IP)
CLUSTER_KUBERNETES_SVC_IP: "{{ service_cidr | ipaddr('net') | ipaddr(1) | ipaddr('address') }}"

# etcd 集群服务地址列表, 根据etcd组成员自动生成
TMP_ENDPOINTS: "{% for h in groups['etcd'] %}https://{{ h }}:2379,{% endfor %}"
ETCD_ENDPOINTS: "{{ TMP_ENDPOINTS.rstrip(',') }}" 


# k8s 集群 master 节点证书配置，可以添加多个ip和域名（比如增加公网ip和域名）
MASTER_CERT_HOSTS:
  - 172.16.106.187
  - 172.16.106.188
  - 172.16.106.189
  #- "10.1.1.1"
  #- "k8s.test.io"
  #- "61.182.11.41"
  #- "www.test.com"
