# 安装目录
ansible_dir: '/app/ansible/deploy_k8s'
software_dir: '/root/software/binary_pkg'
base_dir: '/opt/work'
k8s_work_dir: '/opt/kubernetes'
etcd_work_dir: '/opt/etcd'
tmp_dir: '/tmp/k8s'

# 证书目录
ca_dir: '/etc/kubernetes/ssl'
etcd_ca_dir: '/etc/etcd/ssl'

# 集群网络
service_cidr: '10.254.0.0/16'
cluster_dns: '10.254.0.2'      # 与roles/addons/files/coredns.yaml中IP一致，并且是service_cidr中的IP
pod_cidr: '10.10.0.0/16'       # 与roles/addons/files/kube-flannel.yaml中网段一致
service_nodeport_range: '30000-32767'
cluster_domain: 'cluster.local'

# 高可用，如果部署单Master，该项忽略
vip: '172.16.106.198'
nic: 'eth0' 

# 自签证书可信任IP列表，为方便扩展，可添加多个预留IP
cert_hosts:
  master:
    - 172.16.106.187
    - 172.16.106.188
    - 172.16.106.189

  node:
    - 172.16.106.195
    - 172.16.106.196
    - 172.16.106.197

  # 包含所有etcd节点IP
  etcd:
    - 172.16.106.187
    - 172.16.106.188
    - 172.16.106.189

