---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: haproxy,keepalived安装包
  unarchive: src={{ software_dir }}/ha.tar.gz dest={{ tmp_dir }}

- name: 安装haproxy,keepalived 高可用软件
  yum: name={{ tmp_dir }}/{{ item }} state=present
  with_items:
    - "net-snmp-libs-5.7.2-43.el7.x86_64.rpm"
    - "net-snmp-agent-libs-5.7.2-43.el7.x86_64.rpm"
    - "keepalived-1.3.5-16.el7.x86_64.rpm"
    - "haproxy-1.5.18-9.el7.x86_64.rpm"
    - "psmisc-22.20-16.el7.x86_64.rpm"
