# 设置 dns svc ip (这里选用 SERVICE_CIDR 中第2个IP)
CLUSTER_DNS_SVC_IP: "{{ service_cidr | ipaddr('net') | ipaddr(2) | ipaddr('address') }}"


# node节点最大pod 数
MAX_PODS: 100

KUBE_RESERVED_ENABLED: "yes"
KUBE_RESERVED: "{'cpu':'200m','memory':'500Mi','ephemeral-storage':'1Gi'}"
# k8s 官方不建议草率开启 system-reserved, 除非你基于长期监控，了解系统的资源占用状况；并且随着系统运行时间，需要适当增加资源预留
SYS_RESERVED_ENABLED: "no"
# 以下系统预留设置基于 4c/8g 虚机，最小化安装系统服务，如果使用高性能物理机请适当增加数值
SYS_RESERVED: "{'cpu':'200m','memory':'500Mi','ephemeral-storage':'1Gi'}"

# node 请求 apiserver 负载均衡算法，常见如下：
# "roundrobin": 基于服务器权重的轮询
# "leastconn": 基于服务器最小连接数
# "source": 基于请求源IP地址
# "uri": 基于请求的URI
BALANCE_ALG: "roundrobin"

# 设置 APISERVER 地址
KUBE_APISERVER: "https://{{ vip }}:8443"

# 基础容器镜像
SANDBOX_IMAGE: "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1"
#SANDBOX_IMAGE: "registry.access.redhat.com/rhel7/pod-infrastructure:latest"

# Cluster container-runtime supported: docker, containerd
CONTAINER_RUNTIME: "docker"
