---
- name: 1.准备kube-controller-manager配置文件和签名请求
  template: src={{ item }}.j2 dest={{ base_dir }}/ssl/{{ item }}
  with_items:
  - "kube-controller-manager-csr.json"

- name: 2.创建 kube-controller-manager 证书与私钥
  shell: "cd {{ base_dir }}/ssl/ && \ 
        cfssl gencert \
        -ca={{ base_dir }}/ssl/ca.pem \
        -ca-key={{ base_dir }}/ssl/ca-key.pem \
        -config={{ base_dir }}/ssl/ca-config.json \
        -profile=kubernetes kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager"

- name: 3.设置集群参数
  shell: "kubectl config set-cluster kubernetes \
        --certificate-authority={{ base_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"

- name: 4.设置认证参数
  shell: "kubectl config set-credentials system:kube-controller-manager \
        --client-certificate={{ base_dir }}/ssl/kube-controller-manager.pem \
        --client-key={{ base_dir }}/ssl/kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"

- name: 5.设置上下文参数
  shell: "kubectl config set-context system:kube-controller-manager \
        --cluster=kubernetes \
        --user=system:kube-controller-manager \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"

- name: 6.选择默认上下文
  shell: "kubectl config use-context system:kube-controller-manager \
   --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"
