---
- name: 1.准备kube-proxy配置文件和签名请求
  template: src={{ item }}.j2 dest={{ base_dir }}/ssl/{{ item }}
  with_items:
  - "kube-proxy-csr.json"

- name: 2.创建 kube-proxy证书与私钥
  shell: "cd {{ base_dir }}/ssl/ && \ 
        cfssl gencert \
        -ca={{ base_dir }}/ssl/ca.pem \
        -ca-key={{ base_dir }}/ssl/ca-key.pem \
        -config={{ base_dir }}/ssl/ca-config.json \
        -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy"

- name: 3.设置集群参数
  shell: "kubectl config set-cluster kubernetes \
        --certificate-authority={{ base_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"

- name: 4.设置客户端认证参数
  shell: "kubectl config set-credentials kube-proxy \
        --client-certificate={{ base_dir }}/ssl/kube-proxy.pem \
        --client-key={{ base_dir }}/ssl/kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"

- name: 5.设置上下文参数
  shell: "kubectl config set-context default \
        --cluster=kubernetes \
        --user=kube-proxy \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"

- name: 6.选择默认上下文
  shell: "kubectl config use-context default \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"
