---
- name: 1.准备kube-scheduler配置文件和签名请求
  template: src={{ item }}.j2 dest={{ base_dir }}/ssl/{{ item }}
  with_items:
  - "kube-scheduler-csr.json"

- name: 2.创建 kube-scheduler 证书与私钥
  shell: "cd {{ base_dir }}/ssl/ && \ 
        cfssl gencert \
        -ca={{ base_dir }}/ssl/ca.pem \
        -ca-key={{ base_dir }}/ssl/ca-key.pem \
        -config={{ base_dir }}/ssl/ca-config.json \
        -profile=kubernetes kube-scheduler-csr.json | cfssljson -bare kube-scheduler"

- name: 3.设置集群参数
  shell: "kubectl config set-cluster kubernetes \
        --certificate-authority={{ base_dir }}//ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ base_dir }}/ssl/kube-scheduler.kubeconfig"

- name: 4.设置认证参数
  shell: "kubectl config set-credentials system:kube-scheduler \
        --client-certificate={{ base_dir }}/ssl/kube-scheduler.pem \
        --client-key={{ base_dir }}/ssl/kube-scheduler-key.pem \
        --embed-certs=true \
        --kubeconfig={{ base_dir }}/ssl/kube-scheduler.kubeconfig"

- name: 5.设置上下文参数
  shell: "kubectl config set-context system:kube-scheduler \
        --cluster=kubernetes \
        --user=system:kube-scheduler \
        --kubeconfig={{ base_dir }}/ssl/kube-scheduler.kubeconfig"

- name: 6.选择默认上下文
  shell: "kubectl config use-context system:kube-scheduler \
        --kubeconfig={{ base_dir }}/ssl/kube-scheduler.kubeconfig"
