# 创建admin证书和私钥
# kubectl与apiserver https 安全端口通信，apiserver对提供的证书进行认证和授权。
# kubectl 作为集群的管理工具，需要被授予最高权限，这里创建具有最高权限的admin证书。
---
- name: 1.删除原有kubeconfig
  file: path=/root/.kube/config state=absent
  ignore_errors: true

- name: 2.准备admin配置文件和签名请求
  template: src={{ item }}.j2 dest={{ base_dir }}/ssl/{{ item }}
  with_items:
  - "admin-csr.json"

- name: 3.创建 admin 证书和私钥
  shell: "cd {{ base_dir }}/ssl && \
        cfssl gencert \
        -ca={{ base_dir }}/ssl/ca.pem \
        -ca-key={{ base_dir }}/ssl/ca-key.pem \
        -config={{ base_dir }}/ssl/ca-config.json \
        -profile=kubernetes admin-csr.json | cfssljson -bare admin" 

- name: 4.设置集群参数
  shell: "kubectl config set-cluster kubernetes \
        --certificate-authority={{ base_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }}"

# USER_NAME: admin
- name: 5.设置客户端认证参数
  shell: "kubectl config set-credentials admin \
        --client-certificate={{ base_dir }}/ssl/admin.pem \
        --client-key={{ base_dir }}/ssl/admin-key.pem \
        --embed-certs=true"

- name: 6.设置上下文参数
  shell: "kubectl config set-context kubernetes \
        --cluster=kubernetes --user=admin"

- name: 7.选择默认上下文
  shell: "kubectl config use-context kubernetes"
