---
- name: 创建 docker 存放数据目录
  file: dest={{ DOCKER_DIR }} state=directory

- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 分发并解压docker二进制包
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/docker-*.tgz"

- name: 移动docker二进制文件
  shell: cp -rf {{ tmp_dir }}/docker/* {{ DOCKER_BIN }}

- name: 创建docker配置文件目录
  file: dest=/etc/docker state=directory

- name: 分发service文件
  template: src={{ item }}.j2 dest=/usr/lib/systemd/system/{{ item }}
  with_items:
    - docker.service


- name: 配置参数文件 docker.json
  template: src={{ item }}.j2 dest=/etc/docker/{{ item }}
  with_items:
    - daemon.json

- name: 启动docker
  systemd: name=docker state=restarted enabled=yes daemon_reload=yes

- name: 查看状态
  shell: docker info
  register: docker 
- debug: var=docker.stdout_lines
