- name: 安装基础软件包
  yum: 
    name: 
      - bash-completion     # bash 命令补全工具，需要重新登录服务器生效
      - conntrack-tools     # ipvs 模式需要
      - conntrack           # ipvs 模式需要
      - ipset               # ipvs 模式需要
      - ipvsadm             # ipvs 模式需要
      - libseccomp          # 安装containerd需要
      - nfs-utils           # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - psmisc              # 安装psmisc 才能使用命令killall，keepalive的监测脚本需要
      - rsync               # 文件同步工具，分发证书等配置文件需要
      - socat               # 用于port forwarding
      - jq
      - iptables 
      - bridge-utils         # 加载bridge模块
    state: present




